Sockperf filewrite
orkmellanox/sockperf pull request #124
Opened 2019-08-05 13:05 UTC by garg7pec

2019-08-05 13:06 UTC, swx-jenkins2 commented
Can one of the admins verify this patch?

2019-08-06 10:27 UTC, rafiw requested changes

2019-08-06 10:27 UTC, rafiw commented on src/server.cpp
> +                                retVal = system((createSockperfDirectoryCommand.append(s_user_params.sockperfDumpDataDirectory)).c_str());
Why not to create using the mkdir function?https://codeyarns.com/2014/08/07/how-to-create-directory-using-c-on-linux/

2019-08-06 10:27 UTC, rafiw commented on src/server.h
> +std::string generateDumpFileName(std::string ip)
Where is the IP used?

2019-08-06 10:28 UTC, rafiw commented
Hi @garg7pec thank you for your contribution
What is the motivation of this change?

2019-08-08 10:36 UTC, garg7pec commented
the motive for this change is to add capability in sockperf tool to do the disk writes for the files (in sync manner to be sure that the disk write has happened for sure).

2019-09-25 16:27 UTC, igor-ivanov commented
Hi @garg7pec `sockperf` is considered as a tool to measure performance on network. It seems that motivation you pointed does not meet primary usage case.

2019-12-24 10:35 UTC, igor-ivanov commented
rejected

2019-12-24 10:35 UTC, closed without merging