Christian/add observationbased stats histogram2
orkmellanox/sockperf pull request #146
Opened 2021-03-29 22:32 UTC by ChrisCoe

**Motive:**

Currently, sockperf runs until a timer completes which produces an undetermined number of data rows. Observational-based measurements produce an exact number which eases sockperf run comparisons (such as with stats) and avoids potential overflow during high data collection. Compute more stats directly from measurements to take advantage of sockperf's `ticks` (nanosecond precision). Produce microsecond resolution sparse fixed bin histogram from measurements to provide a visual display of data.

**Changes:**
Obervational-based
- Parser accepts `-n` for number of observations. This measurement type is only for ping-pong mode
- Observational warmup/cooldown when in observational mode instead of adding warmup/cooldown time to timer
- Tracking valid observations in `doSendThenReceiveLoop`, where `client_send_then_receive` is blocking
- Time cap based on warm up sample to limit waiting on observations

Stats
- Add mean absolute deviation, median absolute deviation, semi-interquartile range, coefficient of variance, standard error, and confidence interval 
- Confidence interval significance level configurable via arg flag `--ci_sig_level` (includes decimals)
- Inverse CDF (or ppf) function to compute confidence interval  for any significance level (0-100 exclusive)
- Getter for long name of options for logging purposes
- Sort latency list once where other stats can reuse

Histogram
- Build histogram and display histogram on terminal for a quick view (frequency rounded up)
- Store raw histogram data to log file if present
- Histogram flag, bin size, lower range, and upper range of interest are configurable via cmd args,respectively `-histogram` `--h_bin_size_us` `--h_lower_range_us` `--h_upper_range_us`
- Left and right outlier bins to capture all data outside given range

**Manual Self-Testing:**
Ran server and client locally and manually verified logX.txt had the expected observational data count.
`./sockperf sr -i 127.0.0.1`
`./sockperf pp -i 127.0.0.1 -n 1000 -m 64 --full-log log.txt` -> 1000
`./sockperf pp -i 127.0.0.1 -n 1         -m 64 --full-log logA.txt` -> 1\
`./sockperf pp -i 127.0.0.1 -n -1        -m 64 --full-log logC.txt` -> failed to help page as expected
`./sockperf pp -i 127.0.0.1 -n 100000001 -m 64 --full-log logD.txt` -> failed to help page as expected
`./sockperf pp -i 127.0.0.1 -n 100000000 -m 64 --full-log logE.txt` -> 100000000 (max obs imposed)

`./sockperf pp -i 127.0.0.1 -n 1000 -m 64 --ci_sig_level 80 --full-log log.txt --full-rtt`
All stat changes are reported in magenta line `sockperf: ====> avg-rtt...`.
![image](https://user-images.githubusercontent.com/20761371/108804256-c3639a80-756a-11eb-963c-53ea3cbccb45.png)

`./sockperf pp -i 127.0.0.1 -n 1000000 -m 64 --histogram --h_lower_range_us 25 --h_upper_range_us 60 --h_bin_size_us 1 --full-log log.txt --full-rtt`
All histogram changes are after `sockperf: [Histogram]...`
![histo1](https://user-images.githubusercontent.com/20761371/112075510-e5cee080-8b35-11eb-943e-ea9624217f84.png)

Raw histogram content at the end of log file:
```
------------------------------
histogram was built using the following parameters: --h_bin_size_us=1 --h_lower_range_us=25 --h_upper_range_us=60
------------------------------
bin (usec), frequency
19-25,          360
25,             462
26,             678
27,             667
28,             954
29,             2176
30,             7270
31,             22381
32,             52176
33,             95764
34,             155682
35,             208057
36,             129830
37,             99863
38,             31053
39,             16956
40,             13086
41,             10095
42,             7562
43,             6284
44,             5583
45,             5113
46,             5127
47,             5928
48,             7408
49,             10500
50,             13064
51,             13854
52,             11874
53,             8260
54,             5151
55,             3450
56,             2759
57,             2287
58,             2079
59,             1616
60-12679,               34591
------------------------------
```

2021-03-29 22:35 UTC, swx-jenkins2 commented
Can one of the admins verify this patch?

2021-04-12 17:07 UTC, ChrisCoe commented
Hi @igor-ivanov, did you get a chance to review this PR?

2021-04-13 07:44 UTC, igor-ivanov commented
@ChrisCoe I will try to do it this week

2021-04-15 16:16 UTC, igor-ivanov reviewed
Please look my comments

2021-04-15 16:16 UTC, igor-ivanov commented on src/sockperf.cpp
> +        if (!rc && aopt_check(self_obj, 'n')) {
As I understand `-n` conflicts with `-t`, so please consider explicit check in both cases. See example as
https://github.com/Mellanox/sockperf/blob/sockperf_v2/src/sockperf.cpp#L1573-L1592.

Folowing test stucks on my side.
```
sockperf sr -i 1.1.3.6
sockperf pp -i 1.1.3.6 --mps=2 -n 10
```

Common note:
1. Idea with `-n` is clear
2. I think that it can conflict with some other parameters as `--mps`, `--time` for example
3. Probably resolving conflicts is complex task
4. Consider replacing **observation** with **number** in all places (functions, variables etc). Number name is more obvious. See other benchmark tools for example iperf3 (https://iperf.fr/iperf-doc.php#3num). Observation confuses.

2021-04-15 16:16 UTC, igor-ivanov commented on src/defs.h
> +    uint64_t warmup_obs;
using `uint64_t` for warmup and cooldown comparing with `uint32_t` for counter looks strange

2021-04-15 16:16 UTC, igor-ivanov commented on src/sockperf.cpp
> +                               "traffic, based on timeline and message size." },
potential style check issue

2021-04-15 16:16 UTC, igor-ivanov commented on src/aopt.cpp
> +    }
please do check after initialization

2021-04-15 16:16 UTC, igor-ivanov commented on src/client.cpp
> +
Please fix format output (alignment);
```
sockperf: bin 80-90 #
sockperf: bin 100-110 ####
sockperf: bin 110-120 ######
```

2021-04-15 16:16 UTC, igor-ivanov commented on src/defs.h
> +    OPT_HISTOGRAM_BIN_SIZE,       // 49
Please consider using `--histogram` option to set all related parameters. See `set_affinity_list` as an example.
I think this manner should look better.
For example: `--histogram bin:lower:upper`

2021-06-18 07:37 UTC, ChrisCoe commented on src/sockperf.cpp
> +                               "traffic, based on timeline and message size." },
I don't think this is an issue. I made this formatting change for better alignment in regards to the rest of the modes in the list

2021-06-18 07:42 UTC, ChrisCoe commented
@igor-ivanov I addressed all your feedback and agree with all your suggestions; thanks for the provided examples. Meant to do this much sooner... let me know what you think.

2021-06-18 10:56 UTC, igor-ivanov commented
thank you, @ChrisCoe I will look

2021-07-27 00:33 UTC, ChrisCoe commented
@igor-ivanov Is there an update on this?

2021-07-27 06:22 UTC, igor-ivanov commented
@ChrisCoe still no, i will look and back with feedback

2021-10-01 10:20 UTC, igor-ivanov commented
bot:retest

2021-10-06 15:34 UTC, agalanin-at-nvidia requested changes
Hello, @ChrisCoe! I have some comments regarding parsing code.

2021-10-06 15:34 UTC, agalanin-at-nvidia commented on src/sockperf.cpp
> +                log_msg("-t conflicts with -n option");
The conflict between `-t` and `-n` has already been checked in previous `if` (lines 834-855).

2021-10-06 15:34 UTC, agalanin-at-nvidia commented on src/sockperf.cpp
> +                        arg_index++;
Possible out-of-bounds problem. For example, try to parse string `12:34:56:78:90`.

I suggest you to rewrite parsing code using sscanf:
```c
long bin_size, lower_range, upper_range;
char suffix; //< needed to check for garbage at the end
if (sscanf(optarg, "%ld:%ld:%ld%c", &bin_size, &lower_range, &upper_range, &suffix) == 3) {
    s_user_params.histogram_bin_size = bin_size;
    s_user_params.histogram_lower_range = lower_range;
    s_user_params.histogram_upper_range = upper_range;
} else {
    log_err("Invalid argument: %s "
            "Format should be binsize:lowerrange:upperrange", optarg);
    rc = SOCKPERF_ERR_BAD_ARGUMENT;
}
```

2021-10-06 15:34 UTC, agalanin-at-nvidia commented on src/sockperf.cpp
> +        if(s_user_params.measurement == NUMBER_BASED) {
Please add a space betweeen `if ` and `(`

2021-10-07 15:03 UTC, agalanin-at-nvidia requested changes

2021-10-07 15:03 UTC, agalanin-at-nvidia commented on src/aopt.cpp
> +    while(aopt_desc[i].key != 0) {
It is more common to use `for` loop in this case:
```C
for (int i = 0; aopt_desc[i].key != 0; ++i) {
```

2021-10-07 15:03 UTC, agalanin-at-nvidia commented on src/aopt.cpp
> +    return *aopt_get_desc(aopt_desc, key)->longs;
Check return value of `aopt_get_desc` before dereferencing a pointer. It may be NULL in case of invalid key.

2021-10-07 15:03 UTC, agalanin-at-nvidia commented on src/client.cpp
> +    const int binSize = s_user_params.histogram_bin_size;
It is better to use the same type (uint32_t) as in `defs.h`. The same remark for `getRightOutlierBinIndexReserved`.

2021-10-07 15:03 UTC, agalanin-at-nvidia commented on src/client.cpp
> +int getNumberOfDigits(int input) {
uint32_t input

2021-10-07 15:03 UTC, agalanin-at-nvidia commented on src/client.cpp
> +            (int)g_pApp->m_const_params.histogram_upper_range);
Replace `%d` with `" PRIu32 "` from `<inttypes.h>` to avoid need to cast types.

2021-10-07 15:03 UTC, agalanin-at-nvidia commented on src/client.cpp
> +void storeHistogram(int binSize, std::map<int, int> &activeBins, int minValue, int maxValue) {
Add the `const` modifier to `activeBins` since map content is not altered here.

2021-10-07 15:03 UTC, agalanin-at-nvidia commented on src/sockperf.cpp
> +          "Build histogram of latencies. Optional histogram arguments formated as binsize:lowerrange:upperrange " },
Is the argument really optional? Missing optarg leads to parse error.

2021-10-07 15:03 UTC, agalanin-at-nvidia commented on src/client.cpp
> +    log_msg("%*s %*s", binsHeaderWidth, binsString.c_str(), frequencyHeaderWidth, freqString.c_str());
Two whitespaces before frequencies as in line 203:
```suggestion
    log_msg("%*s  %*s", binsHeaderWidth, binsString.c_str(), frequencyHeaderWidth, freqString.c_str());
```

2021-10-07 15:03 UTC, agalanin-at-nvidia commented on src/client.cpp
> +/* Sparce fixed bin histogram with outlier bins outside given range */
Did you mean "Sparse"?

2021-10-07 15:03 UTC, agalanin-at-nvidia commented on src/client.cpp
> +    activeBins.clear();
Not needed since `activeBins` is a local variable.

2021-10-07 15:03 UTC, agalanin-at-nvidia commented on src/client.cpp
> +            log_msg_file2(f, "[Total Run] RunTime=%.3lf sec; Warm up packets=%" PRIu64
```suggestion
                log_msg_file2(f, "[Total Run] RunTime=%.3lf sec; Warm up packets=%" PRIu64
```

2021-10-07 15:03 UTC, agalanin-at-nvidia commented on src/client.cpp
> +                       "--mps=%d --burst=%d --reply-every=%d --msg-size=%d --number-of-packets=%" PRIu64 "",
`reply-every` parameter is not allowed in ping-pong operation mode where NUMBER_BASED measurement mode can be selected.

2021-10-07 15:03 UTC, agalanin-at-nvidia commented on src/client.cpp
> +            seqNo+= replyEvery;
Since in NUMBER_BASED mode replyEvery is always 1, this code may be simplified.

2021-10-07 15:03 UTC, agalanin-at-nvidia commented on src/client.cpp
> +    int maxStartBinDigits = getNumberOfDigits(maxValue - binSize);
`maxValue` may be less or equal to `binSize`. In these cases `log10` returns NaN or -inf and number of digits is incorrect (< 0). This leads to "freeze" in column formatting code.
```suggestion
    int maxStartBinDigits = getNumberOfDigits(getStartOfRightOutlierBin());
```

2021-10-08 13:38 UTC, igor-ivanov commented on src/sockperf.cpp
> +                log_msg("-t conflicts with -n option");
it is true but i would like to keep this too. To avoid a case when someone moves this code before `-n` option parsing.

2021-10-13 07:50 UTC, ChrisCoe commented on src/client.cpp
> +            (int)g_pApp->m_const_params.histogram_upper_range);
Good point. I had to replace `%d` with `%" PRIu32 "`.

2021-10-13 07:53 UTC, ChrisCoe commented on src/sockperf.cpp
> +                        arg_index++;
Ah, so much cleaner!

2021-10-13 08:05 UTC, ChrisCoe commented on src/sockperf.cpp
> +          "Build histogram of latencies. Optional histogram arguments formated as binsize:lowerrange:upperrange " },
This is outdated. Updated description and aopt type to reflect required args for histogram flag.

2021-10-13 09:03 UTC, agalanin-at-nvidia requested changes

2021-10-13 09:03 UTC, agalanin-at-nvidia commented on src/aopt.cpp
> +    return *aopt_desc->longs;
Result of `aopt_get_desc` is lost. You are always use the first aopt.

2021-10-13 09:03 UTC, agalanin-at-nvidia commented on src/sockperf.cpp
> +                if (sscanf(optarg, "%ld:%ld:%ld%c", &bin_size, &lower_range, &upper_range, &suffix) == required_args) {
Belated comment: you can use `PRIu32` also here and parse directly to `s_user_params.*` without using temporary variables.

2021-10-13 09:05 UTC, ChrisCoe commented
Hey, @agalanin-at-nvidia! I have addressed all your comments. Thank you, and let me know what you think 😊.

2021-10-13 12:40 UTC, agalanin-at-nvidia requested changes

2021-10-13 12:40 UTC, agalanin-at-nvidia commented on src/client.cpp
> +                    (int)g_pApp->m_const_params.sec_test_duration);
NUMBER_BASED mode full-log output is broken after this change (-n 1000):
```
------------------------------
test was performed using the following parameters: --mps=600000 --burst=1 --reply-every=1 --msg-size=64 --time=1
------------------------------
```
Should display `--number-of-packets`, `--msg-size` and `--burst`.

2021-10-14 05:47 UTC, ChrisCoe commented on src/client.cpp
> +                    (int)g_pApp->m_const_params.sec_test_duration);
Got it. Made the change.

2021-10-14 10:10 UTC, agalanin-at-nvidia commented
All my remarks have been fixed. @igor-ivanov, your turn!

2021-10-14 10:27 UTC, igor-ivanov commented
thank you, i see github reports conflicts. @ChrisCoe could you please resolve them before moving to verification team.

2021-10-14 23:08 UTC, ChrisCoe commented
@igor-ivanov Hmm, I don't see any conflicts. I was able to locally merge this branch with the main (sockperf_v2) branch without running into conflicts.

2021-10-28 18:28 UTC, ChrisCoe commented
Would like to clarify here. Is anything needed from me at the moment?

2021-10-29 13:32 UTC, igor-ivanov commented
> Would like to clarify here. Is anything needed from me at the moment?

no
PR is in verification now

2021-11-22 16:41 UTC, igor-ivanov commented
Moved to sockperf_v2 (https://github.com/Mellanox/sockperf/commit/a57ffb5790020021ea1dff2b6b7d9bf5b1669e6d)

2021-11-22 16:41 UTC, closed without merging