issue: 2670645 Add xlio extra api support
orkmellanox/sockperf pull request #149
Opened 2021-05-27 13:13 UTC by igor-ivanov

2021-06-01 14:24 UTC, AlexanderGrissik requested changes
Reviewed all the files and added some comments.
Also there is some modification needed in doc/main.dox which still describes old flags. like --load-vma.

2021-06-01 14:24 UTC, AlexanderGrissik commented on src/vma-redirect.cpp
> +#define XLIO_LOG_CB_ENV_VAR "VMA_LOG_CB_FUNC_PTR"
Maybe change the  name itself to "XLIO_LOG_CB_FUNC_PTR"?

2021-06-01 14:24 UTC, AlexanderGrissik commented on src/sockperf.cpp
> +      "use rate limit (packet-pacing), with XLIO must be run with VMA_RING_ALLOCATION_LOGIC_TX "
VMA_RING_ALLOCATION_LOGIC_TX to XLIO_RING_ALLOCATION_LOGIC_TX ?

2021-06-01 14:24 UTC, AlexanderGrissik commented on src/sockperf.cpp
> +// use it with command such as: VMA ./sockperf -s -f conf/conf.inp --xliorxfiltercb
"... as: VMA ..." to "... as : XLIO ..." ?

2021-06-01 14:24 UTC, AlexanderGrissik commented on src/sockperf.cpp
>              s_user_params.b_server_dont_reply, s_user_params.b_server_detect_gaps,
See lines 3422, 3418
Also didn't find VMA_LIBRARY_MAJOR definition, in libxlio there something like PRJ_LIBRARY_MAJOR.

2021-06-01 14:24 UTC, AlexanderGrissik commented on src/vma-redirect.cpp
see line 176, not sure if it should stay like this ...

2022-09-06 07:59 UTC, swx-jenkins3 commented
Can one of the admins verify this patch?

2022-09-07 08:23 UTC, igor-ivanov commented
Closed because final solution as https://github.com/Mellanox/sockperf/pull/198 is merged

2022-09-07 08:23 UTC, closed without merging