use freeaddrinfo only if getaddrinfo succeeded
orkmellanox/sockperf pull request #179
Opened 2022-04-21 11:10 UTC by EldarShalev

freeaddrinfo might cause segmentation fault if getaddrinfo  wasn't succeeded 
getaddrinfo man page: 
https://man7.org/linux/man-pages/man3/getaddrinfo.3.html

freeaddinfo man page: 
https://linux.die.net/man/3/freeaddrinfo

2022-04-21 11:14 UTC, agalanin-at-nvidia requested changes

2022-04-21 11:14 UTC, agalanin-at-nvidia commented on src/sockperf.cpp
> +    if (res ==0)
please, append this to previous `if`

2022-04-21 11:23 UTC, swx-jenkins3 commented
Can one of the admins verify this patch?

2022-04-25 06:27 UTC, agalanin-at-nvidia approved these changes

2022-04-25 08:25 UTC, igor-ivanov approved these changes

2022-04-28 10:01 UTC, vasily-v-ryabov commented
bot:retest

2022-05-26 12:31 UTC, agalanin-at-nvidia commented
@EldarShalev, rebase this PR, please.

2022-05-30 08:50 UTC, EldarShalev commented
> @EldarShalev, rebase this PR, please.

Done.

2022-05-30 08:52 UTC, agalanin-at-nvidia requested changes

2022-05-30 08:52 UTC, agalanin-at-nvidia commented on src/sockperf.cpp
> +
must be #ifdef

2022-05-30 12:30 UTC, EldarShalev commented on src/sockperf.cpp
> +
Fixed (was a mistake)

2022-05-30 12:30 UTC, agalanin-at-nvidia approved these changes

2022-05-30 13:31 UTC, merged